In [7]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# Tensores con valores conocidos

<img src="figures/tensores con valores conocidos.jpg" width="50%">

# Función Constant
1. Crear un Tensor unidimensional que contenga tres valores de coma flotante

<img src="figures/tensores constantes.png" width="50%">

In [6]:

t1 = tf.constant([1.2, 2.3, 3.4])

with tf.compat.v1.Session() as sess:
    print(sess.run(t1))



[1.2 2.3 3.4]


2. Crear una matriz 2-x-2 y establece cada uno de sus elementos a la letra c

In [9]:
t2 = tf.constant([['c', 'c'], ['c', 'c']])
with tf.compat.v1.Session() as sess:
    print(sess.run(t2))


[[b'c' b'c']
 [b'c' b'c']]


In [13]:
t3 = tf.constant([4,2], tf.int16, [2])
with tf.compat.v1.Session() as sess:
    print(sess.run(t3))


[4 2]


# Función zeros
Crea un tensor con todos los elementos establecidos en cero

In [17]:
zero_tensor = tf.zeros([3])

with tf.compat.v1.Session() as sess:
    print(sess.run(zero_tensor))

[0. 0. 0.]


In [18]:
zero_tensor2 = tf.zeros([3,4], tf.int32)
with tf.compat.v1.Session() as sess:
    print(sess.run(zero_tensor2))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Función ones
Dado un solo tensor ( tensor ), esta operación devuelve un tensor del mismo tipo y forma que el tensor con todos los elementos establecidos en 1.

In [20]:
ones_tensor = tf.ones([2,3], tf.int32)
with tf.compat.v1.Session() as sess:
    print(sess.run(ones_tensor))

[[1 1 1]
 [1 1 1]]


# Función fill
Crea un tensor relleno con un valor escalar.

In [21]:
tf.fill ([2,3], 9)

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

# Función Linspace
Genera valores espaciados uniformemente en un intervalo a lo largo de un eje dado.

In [22]:
lin_tensor = tf.linspace(10.0, 20.0, 5)
with tf.compat.v1.Session() as sess:
    print(sess.run(lin_tensor))


[10.  12.5 15.  17.5 20. ]


# Función Range
Crea una secuencia de números.

In [23]:
start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)

<tf.Tensor 'range:0' shape=(5,) dtype=int32>