In [5]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()


# Operaciones con tensores

  * inicializar y asignar las variables de TensorFlow
  * crear y manipular tensores
  * repasar la suma y el producto en álgebra lineal (si estos temas son nuevos para ti, consulta una introducción a la [suma]
  * familiarizarte con operaciones básicas de matemática y matrices de TensorFlow

 ## Suma de vectores

Puedes realizar muchas operaciones matemáticas en los tensores ([TF API](https://www.tensorflow.org/api_guides/python/math_ops)). El siguiente código crea y manipula dos vectores (tensores 1-D), cada uno con seis elementos:

In [9]:

detection_graph = tf.compat.v1.get_default_graph()

with detection_graph.as_default():
  # Crea un vector de seis elementos (1-D tensor).
  primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

 # Crea otro vector de seis elementos. Cada elemento en el vector será
  # inicializado a 1. El primer argumento es la forma del tensor (más
  # en las formas a continuación)
  ones = tf.ones([6], dtype=tf.int32)

  # Suma los dos vectores. El tensor resultante es un vector de seis elementos
  just_beyond_primes = tf.add(primes, ones)

  # Cree una sesión para ejecutar el gráfico predeterminado.
  with tf.compat.v1.Session() as sess:
    print(just_beyond_primes.eval())



[ 3  4  6  8 12 14]


 ### Emisión

En términos matemáticos, solo puedes realizar operaciones basadas en elementos (p. ej., *suma* e *iguales*) en los tensores de la misma forma. Sin embargo, en TensorFlow, puedes realizar operaciones en tensores que tradicionalmente eran incompatibles. TensorFlow es compatible con la **emisión** (un concepto acuñado de NumPy), donde la matriz más pequeña en una operación basada en elementos se amplía para que tenga la misma forma que la matriz más grande. Por ejemplo, mediante la emisión:

* Si un operando requiere un tensor de tamaño `[6]`, un tensor de tamaño `[1]` o `[]` puede servir como operando.
* Si un operando requiere un tensor de tamaño `[4, 6]`, cualquiera de los siguientes tamaños puede servir como operando:
  * `[1, 6]`
  * `[6]`
  * `[]`
* Si una operación requiere un tensor de tamaño `[3, 5, 6]`, cualquiera de los siguientes tamaños puede servir como operando:

  * `[1, 5, 6]`
  * `[3, 1, 6]`
  * `[3, 5, 1]`
  * `[1, 1, 1]`
  * `[5, 6]`
  * `[1, 6]`
  * `[6]`
  * `[1]`
  * `[]`
  
**NOTA:** Cuando un tensor es de emisión, sus entradas se **copian** conceptualmente. (Por cuestiones de rendimiento, no se copian realmente; la emisión se creó como una optimización del rendimiento).

El conjunto de reglas completo de la emisión se describe en detalle en la [documentación sobre la emisión de NumPy](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html).

El siguiente código realiza la misma suma de tensores que antes, pero mediante la emisión:

In [10]:
with detection_graph.as_default():
  # Create a six-element vector (1-D tensor).
  primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

  # Create a constant scalar with value 1.
  ones = tf.constant(1, dtype=tf.int32)

  # Add the two tensors. The resulting tensor is a six-element vector.
  just_beyond_primes = tf.add(primes, ones)

  with tf.compat.v1.Session() as sess:
    print(just_beyond_primes.eval())

[ 3  4  6  8 12 14]


 ## Producto de arreglos

En álgebra lineal, cuando se multiplican dos arreglos, la cantidad de *columnas* del primer arreglo debe ser igual a la cantidad de *filas* en el segundo arreglo.

- Es **_válido_** para multiplicar un arreglo de `3 × 4` por uno de `4 × 2`. El resultado será un arreglo de `3 × 2`.
- Es **_inválido_** para multiplicar un arreglo de `4 × 2` por uno de `3 × 4`.

In [11]:
with detection_graph.as_default():
  # Cree una matriz (tensor 2-d) con 3 filas y 4 columnas.
  x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                  dtype=tf.int32)

  # Crea una matriz con 4 filas y 2 columnas.
  y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

  #Multiplica `x` por `y`.
  # La matriz resultante tendrá 3 filas y 2 columnas.
  matrix_multiply_result = tf.matmul(x, y)

  with tf.compat.v1.Session() as sess:
    print(matrix_multiply_result.eval())

[[35 58]
 [35 33]
 [ 1 -4]]


 ## Cambio de formas de tensores

Dado que la suma de tensores y el producto de arreglos tienen restricciones en los operandos, los programadores de TensorFlow con frecuencia deben cambiar la forma de los tensores.

Para cambiar la forma de un tensor, puedes usar el método `tf.reshape`.
Por ejemplo, puedes cambiar la forma de un tensor de 8 × 2 a uno de 2 × 8 o 4 × 4:

In [16]:
with detection_graph.as_default():
 # Cree una matriz de 8x2 (tensor 2-D).
  matriz = tf.constant([[1,2], [3,4], [5,6], [7,8],[9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)

  # Reshape  la matriz de 8x2 en una matriz de 2x8.
  reshaped_2x8_matrix = tf.reshape(matriz, [2,8])
  
  # Reshape la matriz de 8x2 en una matriz de 4x4
  reshaped_4x4_matrix = tf.reshape(matriz, [4,4])

  with tf.compat.v1.Session() as sess:
    print("Original matrix (8x2):")
    print(matriz.eval())
    print("Reshaped matrix (2x8):")
    print(reshaped_2x8_matrix.eval())
    print("Reshaped matrix (4x4):")
    print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


 
También puedes usar `tf.reshape` para cambiar la cantidad de dimensiones (la "clasificación") del tensor.
Por ejemplo, puedes cambiar la forma de un tensor de 8 × 2 a uno de 3-D de 2 × 2 × 4 o uno de 1-D de 16 elementos.

In [17]:
with tf.Graph().as_default():
  # Cree una matriz de 8x2 (tensor 2-D).
  matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                        [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)

  # Reshape la matriz de 8x2 en un tensor tridimensional de 2x2x4.
  reshaped_2x2x4_tensor = tf.reshape(matrix, [2,2,4])
  
  # Reshape la matriz 8x2 en un tensor 1-D de 16 elementos.
  one_dimensional_vector = tf.reshape(matrix, [16])

  with tf.compat.v1.Session() as sess:
    print("Original matrix (8x2):")
    print(matrix.eval())
    print("Reshaped 3-D tensor (2x2x4):")
    print(reshaped_2x2x4_tensor.eval())
    print("1-D vector:")
    print(one_dimensional_vector.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped 3-D tensor (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1-D vector:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


# Variables, Inicialización y asignación
Hasta el momento, todas las operaciones que realizamos fueron en valores estáticos (tf.constant); al invocar a eval(), el resultado fue siempre el mismo. TensorFlow permite definir objetos de Variable, cuyos valores pueden modificarse.

Cuando se crea una variable, puedes establecer un valor inicial de forma explícita o usar un inicializador (como una distribución):

In [21]:
g = tf.Graph()
with g.as_default():
 # Crea una variable con el valor inicial 3.
  v = tf.Variable([3])

  # Crea una variable de forma [1], con un valor inicial aleatorio,
  # muestreado de una distribución normal con media 1 y desviación estándar 0.35.
  w = tf.Variable(tf.random.normal([1], mean=1.0, stddev=0.35))

 Una particularidad de TensorFlow es que la **inicialización de variables no es automática**. 
 La forma más fácil de inicializar una variable es invocando a global_variables_initializer. Ten en cuenta el uso de Session.run(), que es prácticamente equivalente a eval().

In [24]:


with g.as_default():
  with tf.compat.v1.Session() as sess:
    initialization = tf.compat.v1.global_variables_initializer()
    sess.run(initialization)
   # Ahora, se puede acceder a las variables normalmente y tener valores asignados a ellas.
    print(v.eval())
    print(w.eval())


[3]
[0.63418776]


 Para cambiar el valor de una variable, usa el operando `assign`. Ten en cuenta que, con solo crear el operando `assign`, no se obtendrá ningún efecto. Al igual que con la inicialización, deberás ejecutar el operando de asignación para actualizar el valor de la variable:

In [28]:
with g.as_default():
  with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    # This should print the variable's initial value.
    print(v.eval())

    assignment = tf.compat.v1.assign(v, [7])
    # The variable has not been changed yet!
    print(v.eval())

    # Execute the assignment op.
    sess.run(assignment)
    # Now the variable is updated.
    print(v.eval())

[3]
[3]
[7]
