In [5]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# Tensores con Valores Aleatorios

<img src="figures/tensoresaleatorios.jpg" width="50%">

# Función RandomUniform

In [4]:
valores_aleatorios = tf.random.uniform([10], dtype=tf.float32)

with tf.compat.v1.Session() as sess:
    print(sess.run(valores_aleatorios))

[0.5465491  0.5088934  0.9763385  0.14645493 0.698522   0.79078376
 0.97878635 0.52607083 0.6338397  0.06080484]


# Funciones para transformar los tensores

**Función Reshape**: devuelve un tensor con los mismos elementos que el tensor dado con la forma dada

In [6]:
vector= tf.constant([1.,2.,3.,4.])
matriz= tf.reshape(vector, [2,2])
with tf.compat.v1.Session() as sess:
    print(sess.run(matriz))

[[1. 2.]
 [3. 4.]]


**Función slice**: extrae una porción de un tensor

In [6]:
matris = tf.constant([[1.,2., 3.],[4.,5.,6.], [7.,8.,9.]])
slice_matriz= tf.slice(matris, [1,1], [2,2])
with tf.compat.v1.Session() as sess:
    print(sess.run(slice_matriz))

[[5. 6.]
 [8. 9.]]


**Funcion stack**: combina una lista de tensores en un tensor de mayor rango

In [7]:
t1 =tf.constant([1.,2.])
t2 =tf.constant([3.,4.])
t3 =tf.constant([5.,6.])
t4= tf.stack([t1,t2,t3])

with tf.compat.v1.Session() as sess:
    print(sess.run(t4))

[[1. 2.]
 [3. 4.]
 [5. 6.]]


**Función unstack**: separa un tensor en una lista de tensores de menor rango

In [9]:
t5 =tf.constant([1.,2.])
t6 =tf.constant([3.,4.])
t7 =tf.constant([5.,6.])
t8= tf.unstack([t5,t6,t7])

with tf.compat.v1.Session() as sess:
    print(sess.run(t8))

[array([1., 2.], dtype=float32), array([3., 4.], dtype=float32), array([5., 6.], dtype=float32)]


# Operaciones mateáticas básicas

**add**: suma dos tensores

In [10]:
a = tf.constant([1.,2.,3.])
b = tf.constant([4.,5.,6.])
sum = tf.add(a,b)
suma2 = a+b

**subtract**: resta dos tensores

In [11]:
res =tf.subtract(a,b)

**multiply**: multiplica dos tensores

In [12]:
producto = tf.multiply(a,b)

**divide**: divide dos tensores

In [13]:
div= tf.divide(a,b)

In [14]:
with tf.compat.v1.Session() as sess:
    print(sess.run(sum))
    print(sess.run(suma2))
    print(sess.run(res))
    print(sess.run(producto))
    print(sess.run(div))

[5. 7. 9.]
[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]
